In [1]:
import numpy as np
from typing import Iterable
import torch
from torch import nn

In [9]:
class BaseQuantumCircuit(object):
    def __init__(self, **kwargs):
        self.circuit = nn.Sequential()

In [22]:
class BaseQuantumObject(object):
    def __init__(self, **kwargs):
        self.__define__(**kwargs)
    
    def __define__(self, **kwargs):
        for key, value in kwargs.items():
            setattr(self, key, value)
    
    def __norm__(self, inp):
        pass


In [23]:
class BaseQubit(BaseQuantumObject):
    def __init__(self):
        super().__init__()

In [24]:
class BaseGate(BaseQuantumObject):
    def __init__(self):
        super().__init__()

In [25]:
base_quantum = BaseQuantumObject(inp_state=torch.Tensor((0, 1)), num_states=2, adjoint=False)
print(base_quantum.inp_state)
print(base_quantum.num_states)
print(base_quantum.adjoint)

tensor([0., 1.])
2
False


In [88]:
plus_real = torch.tensor((1, 1), dtype=torch.float32).reshape((1, 2, 1))
plus_imag = torch.tensor((0, 0), dtype=torch.float32).reshape((1, 2, 1))
plus = torch.concat((plus_real, plus_imag), dim=0)
plus_conj = plus.transpose(-1, -2)
conj_multiplier = torch.tensor((1, -1), dtype=torch.int32).reshape((2, 1, 1))
plus_conj = plus_conj * conj_multiplier
norm_const = torch.sqrt(torch.abs(torch.matmul(plus_conj, plus)).sum(dim=0))
# norm_const = torch.where(norm_const==0, 1, norm_const)
print(norm_const)
print(norm_const.shape)

tensor([[1.4142]])
torch.Size([1, 1])


In [89]:
h_real = torch.tensor(((1, 1), (1, -1)), dtype=torch.float32).reshape((1, 2, 2))
h_imag = torch.tensor(((0, 0), (0, 0)), dtype=torch.float32).reshape((1, 2, 2))
h = torch.concat((h_real, h_imag), dim=0)
h_conj = h.transpose(-1, -2)
conj_multiplier = torch.tensor((1, -1), dtype=torch.int32).reshape((2, 1, 1))
h_conj = h_conj * conj_multiplier
norm_const = torch.sqrt(torch.abs(torch.matmul(h_conj, h)).sum(dim=0))
norm_const = torch.where(norm_const==0, 1, 1/norm_const)
h = h / norm_const
print(norm_const)

tensor([[0.7071, 1.0000],
        [1.0000, 0.7071]])
