Scratch work to find an efficient way to generate a complete set of bases.


This will be useful for defining larger ensembles, as the size of the space will scale as 2**n for n qubits in the ensemble.

In [1]:
import torch
from torch import nn

In [6]:
def define_basis(num_qubits):
    initial_basis = torch.arange(2).reshape((-1, 1))
    for i in range(num_qubits-1):
        copy_basis = initial_basis.clone()
        new_zeros = torch.zeros((copy_basis.shape[0], 1))
        new_ones = torch.ones((copy_basis.shape[0], 1))
        new_order_of_magnitude = torch.cat((new_zeros, new_ones), dim=0)
        new_basis = torch.cat((initial_basis, copy_basis), dim=0)
        new_basis = torch.cat((new_order_of_magnitude, new_basis), dim=1)
        initial_basis = new_basis
    return initial_basis.type(torch.uint8)

In [7]:
basis = define_basis(num_qubits=4)
print(basis.shape)
print(basis)

torch.Size([16, 4])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 0, 1, 1],
        [0, 1, 0, 0],
        [0, 1, 0, 1],
        [0, 1, 1, 0],
        [0, 1, 1, 1],
        [1, 0, 0, 0],
        [1, 0, 0, 1],
        [1, 0, 1, 0],
        [1, 0, 1, 1],
        [1, 1, 0, 0],
        [1, 1, 0, 1],
        [1, 1, 1, 0],
        [1, 1, 1, 1]], dtype=torch.uint8)


In [8]:
zero = torch.tensor([[1, 0]]).reshape((1, 2, 1))
one = torch.tensor([[0, 1]]).reshape((1, 2, 1))

print(zero)
print(one)

tensor([[[1],
         [0]]])
tensor([[[0],
         [1]]])
